### ISSUE TITLE
Any plans to support Debian LTS?

### ISSUE THREAD

**Issue by sabrinamile** [oliver/check_os_release#13]
Hey there, thanks for the great plugin.
Are there any plans to support Debian LTS, too? Or maybe support some kind of an import flag for own csv-files with the missing data?
Thanks!

**Comment by oliver** [comment]
Hi, there are currently no plans for Debian LTS support - sorry! I just don't see an easy way to add this. It would be a useful feature, though! I guess it would require that someone maintains a custom CSV file for this info (similar to the RHEL info that was suggested in #11).

To add general support for custom CSV files, the internal checking code would have to support the custom fields as well; so this is more complicated than a simple import. Or maybe there is an easy way and I just don't see it :-)

I will leave this issue open as a reminder; but I cannot say when I will get around to work on this myself. Feel free to send a pull request, though!

**Comment by oliver** [comment]
Looks like the debian.csv file from distro-info-data already contains Debian-LTS dates in its latest versions. Somehow I didn't even check that 🤦‍♂️ - oops! PR #14 is now merged, so this issue should be fixed.
