### ISSUE TITLE
Don't download CSVs from salsa.debian.org any more

### ISSUE THREAD

**Issue by oliver** [oliver/check_os_release#7]
The two CSV files at https://salsa.debian.org/debian/distro-info-data cannot be downloaded any more, with HTTP error 403 "Forbidden, restricted to authenticated users". I don't know if that's a temporary measure or if the admins want to permanently prevent automatic downloading from scripts like these (see also https://github.com/hobbyquaker/check_os_release/issues/2#issuecomment-644975192). I didn't find any mention of this block at eg. https://salsa.debian.org/salsa/support/-/issues. But it would be good to find a solution that does not involve periodic accesses to salsa.debian.org from each user.

Possible solution:
- mirror https://salsa.debian.org/debian/distro-info-data repo to another place (eg. Github)
- set that repo as default download location
- allow specifying the "base directory" for these CSV files on command line, and accept local paths and URLs as parameter

This way the script still works out of the box without requiring any packages to be installed or kept up-to-date; but if people want to avoid a runtime dependency on Github (or on any internet service), they can specify the path to their local distro-info-data directory.

Open Points:
- how to keep the Github mirror updated automatically?
- should there be a shorter/easier command line parameter to switch to the local distro-info-data directory?

**Comment by stefanor** [comment]
FYI: https://bugs.debian.org/973904

**Comment by oliver** [comment]
Fixed with 787277b06ae8108e2cddb2883d1e9f4d0d9d81b5 and 668ae089d2f9f1049a96f598832dccac52ac9aca.

@stefanor: many thanks for providing the data for download. I much appreciate that you took the trouble to solve this problem that isn't yours in a way that helps others!
