### ISSUE TITLE
check_os_release for oracle Linux

### ISSUE THREAD

**Issue by thobus** [oliver/check_os_release#8]
I am looking for a icinga plugin to check the eol state of Oracle Linux OS.
Any ideas to get this running?

**Comment by oliver** [comment]
This might be difficult. You would need an URL where the support cycles of Oracle Linux are listed.

For Debian and Ubuntu this is maintained at https://salsa.debian.org/debian/distro-info-data/ , but I don't know of any such data for Oracle Linux (or for RHEL or CentOS, which AFAIK have similar support cycles).

If you find such a list (in machine-readable format, eg. in CSV or JSON format), feel free to post a link here. Maybe I can try to add support for it.

**Comment by thobus** [comment]
This is the official website, where you find lifetime support data.
https://www.oracle.com/us/support/library/elsp-lifetime-069338.pdf

**Comment by oliver** [comment]
Well, this is not really machine-readable (the check_os_release script would have to extract the dates from the PDF; and also the format of the PDF looks like it can change whenever Oracle changes its document design). So, sorry, but I don't want to add support for this PDF to the script.

If you really need this functionality, you could create a fork of the script and add the dates from the PDF manually. You'd have to check the PDF for changes every month or so, though, and then update the script manually.

**Comment by thobus** [comment]
Hello Oliver, we solved it with a own greated csv file, which we provide via ansible and manage central.
I had to adapt few things in your Phyton script and known the icinga check works.

**Comment by oliver** [comment]
Great, good to hear you got it solved! If you like, you can also attach your CSV file to this issue, so other people can use it as well.

**Comment by thobus** [comment]
[oracle.csv](https://github.com/oliver/check_os_release/files/6966591/oracle.csv)

**Comment by thobus** [comment]
This part i had to change:

**Ubuntu:**
currentCodename = subprocess.check_output(["lsb_release", "--codename", "--short"]).rstrip("\n")
currentReleaseData = None

**Oracle:**
currentCodename = subprocess.check_output(["lsb_release", "-r", "-s"]).rstrip("\n")
currentCodename = re.sub('[0-9]+$', 'x', currentCodename)
currentReleaseData = None

**Comment by oliver** [comment]
Thanks, that's good to know!
